version: '3.8'

services:
  api:
    container_name: nest
    image: nestjs-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${NEST_API_PORT}:${NEST_API_PORT}
    networks:
      - nestjs-network
    depends_on:
      - db
    env_file:
      - /.env
    volumes:
      - ./src:/app/src
    restart: always

  db:
    container_name: postgres
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    networks:
      - nestjs-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    ports:
      - ${POSTGRES_DBEAVER_PORT}:${POSTGRES_PORT}
    restart: always

networks:
  nestjs-network:
    driver: bridge
