version: '3.8'

services:
  api:
    container_name: nest
    image: nestjs
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    ports:
      - ${NEST_API_PORT}:${NEST_API_PORT}
    networks:
      - nestjs-network
    depends_on:
      - db
    env_file:
      - /.env
    restart: always

  db:
    container_name: postgres
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    networks:
      - nestjs-network
    volumes:
      - data-volume:/var/lib/postgres:16.0-alpine
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    ports:
      - ${POSTGRES_DBEAVER_PORT}:${POSTGRES_PORT}
    restart: always

volumes:
  data-volume:

networks:
  nestjs-network:
    driver: bridge
