version: '3.8'

services:

  api:
    container_name: nest
    image: nestjs-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    networks:
      - nestjs-network
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    restart: always

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: "${POSTGRES_DB_PREFIX}_${POSTGRES_DB_NAME}"
    env_file:
      - ./.env
    networks:
      - nestjs-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

networks:
  nestjs-network: